df <- read.csv("household_power_consumption.txt", sep=";", na.strings="?", colClasses=c(rep("character", 2),rep("numeric",7)))
plotDf <- subset(df, Date == "1/2/2007" | Date == "2/2/2007")
plotDf$Timestamp <- with(plotDf, strptime(paste(Date, Time), "%d/%m/%Y %H:%M:%S"))
png("plot3.png", width=480, height=480)
with(plotDf, plot(Timestamp, Sub_metering_1, type="l", ylab="Energy sub metering", xlab=""))
with(plotDf, lines(Timestamp, Sub_metering_2, col="red", xlab="", ylab=""))
with(plotDf, lines(Timestamp, Sub_metering_3, col="blue", xlab="", ylab=""))
legend('topright', c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), col=c("black","red", "blue"), lty=c(1,1,1))
dev.off()
